version: "3"
services:
  odoo:
    image: odoo:14.0
    container_name: odoo14
    ports:
      - 8069:8069
    environment:
      - DB_ENV_POSTGRES_USER=odoo
      - DB_ENV_POSTGRES_PASSWORD=odoo
    links:
      - db:db
    volumes:
      - ./extra-addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./filestore:/var/lib/odoo
    network_mode: "bridge"
    restart: always
  db:
    image: postgres:10.0
    container_name: odoo14_db
    hostname: odoo14_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - ./data:/var/lib/postgresql/data
    network_mode: "bridge"
    restart: always
